(function(){
const GEO='https://raw.githubusercontent.com/tbrugz/geodata-br/master/geojson/geojs-23-mun.json';
let map,ready=false,loading,byName={},pins;
const n=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const base={'Grande Fortaleza':'Fortaleza','Cariri':'Juazeiro do Norte','Centro-Sul':'Iguatu','Sertão dos Inhamuns':'Tauá','Litoral Norte':'Trairi','Sertão de Sobral e Vale do Jaguaribe':'Sobral','Sertão Central':'Quixadá','Serra da Ibiapaba':'Tianguá'};
const town={'palestina do cariri':'Mauriti',altovermelho:'Mauriti',betel:'Juazeiro do Norte',aiuaba:'Aiuaba',jucas:'Jucás',taua:'Tauá',ico:'Icó',limacampos:'Icó',oros:'Orós',palestina:'Acopiara',vilasãopedro:'Iguatu',brejosanto:'Brejo Santo',milagres:'Milagres',trairi:'Trairi',madeira:'Boa Viagem',hermom:'Fortaleza',luzdomundo:'Fortaleza',beberibe:'Beberibe',boaviagem:'Boa Viagem',fariasbrito:'Farias Brito',guassusse:'Orós',quixeramobim:'Quixeramobim',senadorpompeu:'Senador Pompeu',castelao:'Fortaleza',curio:'Fortaleza',aracati:'Aracati',quixada:'Quixadá',cordeiro:'Fortaleza',sobral:'Sobral',barbalha:'Barbalha',campossales:'Campos Sales',iguatu:'Iguatu',crato:'Crato',jardim:'Jardim',mauriti:'Mauriti',tiangua:'Tianguá',vacaria:'Iguatu',varzeaalegre:'Várzea Alegre',icarai:'Caucaia',iguape:'Aquiraz',barrocao:'Caucaia',quixariu:'Campos Sales','novo juazeiro':'Juazeiro do Norte'};
function city(x){let z=n((x.name||'')+' '+(x.address||''));for(const k in town)if(z.includes(k))return town[k];let m=(x.name||'').match(/(?: em| de) ([A-Za-zÀ-ÿ ]+)$/i);return m?m[1].trim():(base[x.region]||'Fortaleza')}
function load(){if(window.L)return Promise.resolve();if(loading)return loading;loading=new Promise((yes,no)=>{let s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=yes;s.onerror=no;document.head.appendChild(s)});return loading}
function detail(x){let d=document.createElement('div'),b=document.createElement('button');d.innerHTML='<b>'+esc(x.name)+'</b><span>'+esc(city(x))+' · '+esc(x.region)+'</span><br>';b.className='btn';b.style.marginTop='8px';b.style.minHeight='32px';b.textContent='Abrir ficha';b.onclick=()=>{document.querySelector('[data-view="directory"]').click();$('#search').value=x.name;render();window.scrollTo({top:0,behavior:'smooth'})};d.appendChild(b);return d}
function cityChurches(name){return churches.filter(x=>n(city(full(x)))===n(name))}
function goChurch(name){document.querySelector('[data-view="directory"]').click();$('#search').value=name;render();window.scrollTo({top:0,behavior:'smooth'})}
function population(id){return fetch('https://apisidra.ibge.gov.br/values/t/9514/n6/'+id+'/v/93/p/2022').then(r=>r.json()).then(a=>{let x=Array.isArray(a)&&a.find(v=>v.V!=null);return x&&x.V?Number(String(x.V).replace(/\./g,'').replace(',','.')):null})}
function showTown(name,id){let list=cityChurches(name),p=document.querySelector('#townPanel');if(!p)return;p.innerHTML='<b>'+esc(name)+'</b><p id="townPopulation">População: consultando IBGE…</p><p><strong>'+list.length+'</strong> igreja'+(list.length===1?'':'s')+' cadastrada'+(list.length===1?'':'s')+' neste município.</p>'+(list.length?'<ul class="town-list">'+list.map(x=>'<li><button data-church="'+esc(x.name)+'">'+esc(x.name)+'</button></li>').join('')+'</ul>':'<p>Este município ainda não possui igreja cadastrada.</p>')+'<p style="font-size:.76rem">População: Censo Demográfico 2022 — IBGE.</p>';p.querySelectorAll('[data-church]').forEach(b=>b.onclick=()=>goChurch(b.dataset.church));population(id).then(v=>{let e=document.querySelector('#townPopulation');if(e)e.textContent=v?'População: '+v.toLocaleString('pt-BR')+' habitantes':'População: dado não disponível'}).catch(()=>{let e=document.querySelector('#townPopulation');if(e)e.textContent='População: consulta indisponível no momento'})}
function summary(){let a=document.querySelector('#mapChurchCount'),b=document.querySelector('#mapTownCount'),covered=new Set(churches.map(x=>n(city(full(x))))).size;if(a)a.textContent=churches.length;if(b)b.textContent=covered}
function drawPins(){if(!ready)return;if(pins)map.removeLayer(pins);pins=L.layerGroup().addTo(map);churches.forEach((x,i)=>{let y=full(x),p;if(y.lat&&y.lng&&Number.isFinite(+y.lat)&&Number.isFinite(+y.lng))p=[+y.lat,+y.lng];else{let m=byName[n(city(y))],q=m?m.getBounds().getCenter():{lat:-3.73,lng:-38.52},a=i*2.39996,r=.0018*(1+i%6);p=[q.lat+Math.sin(a)*r,q.lng+Math.cos(a)*r]}L.marker(p,{title:y.name,icon:L.divIcon({className:'church-pin',iconSize:[22,22],iconAnchor:[11,11]})}).bindTooltip(esc(y.name),{direction:'top',offset:[0,-8],opacity:.98,sticky:true}).bindPopup(detail(y),{maxWidth:240}).addTo(pins)});summary()}
function start(){if(ready){setTimeout(()=>map.invalidateSize(),80);summary();return}let el=document.querySelector('#geoMap');if(!el)return;load().then(()=>fetch(GEO).then(r=>r.json())).then(data=>{map=L.map(el,{minZoom:7,maxZoom:13,preferCanvas:true});map.fitBounds([[-7.55,-41.55],[-2.65,-37.05]]);map.setMaxBounds([[-8.4,-42.4],[-2.05,-36.3]]);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Imagery © Esri',maxZoom:18}).addTo(map);let active=new Set(churches.map(x=>n(city(full(x)))));L.geoJSON(data,{style:f=>({color:'#f8fafc',weight:.65,fillColor:active.has(n(f.properties.name))?'#86efac':'#183b69',fillOpacity:active.has(n(f.properties.name)) ? .16 : .30}),onEachFeature:(f,l)=>{byName[n(f.properties.name)]=l;l.bindTooltip(f.properties.name,{sticky:true,direction:'top',opacity:.94});l.on('click',()=>{l.openTooltip();showTown(f.properties.name,f.properties.id)})}}).addTo(map);['Fortaleza','Maracanaú','Caucaia','Sobral','Tianguá','Quixadá','Canindé','Iguatu','Juazeiro do Norte','Crato','Aracati','Russas','Tauá'].forEach(q=>{let m=byName[n(q)];if(m)L.marker(m.getBounds().getCenter(),{interactive:false,icon:L.divIcon({className:'map-citylabel',html:q,iconSize:[110,18],iconAnchor:[55,9]})}).addTo(map)});ready=true;drawPins();setTimeout(()=>map.invalidateSize(),100)}).catch(()=>{el.innerHTML='<p style="padding:24px">Não foi possível carregar o mapa agora. Verifique a conexão e tente novamente.</p>'})}
window.refreshChurchMap=()=>{drawPins();summary()};
document.querySelector('#mapChurchList')?.addEventListener('click',()=>goChurch(''));document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==b.dataset.view);if(b.dataset.view==='mapview')start()}));
}());